name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd "pg_isready -U test_user" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Setup application-test.properties
        run: |
          echo -e "spring.datasource.url=jdbc:postgresql://localhost:5432/test_db\nspring.datasource.username=test_user\nspring.datasource.password=test_password\nspring.jpa.hibernate.ddl-auto=update\nspring.security.disable-csrf=true" > src/test/resources/application-test.properties
      - name: Set Environment Variables
        env:
          SHOW_SQL: true                # Enable SQL logging if desired
          JWT_SECRET: 'yTiDyInN9Hm2oHRNwAevgDM+WsZROx5310DpcpUFXCo='    # Replace with your actual JWT secret or GitHub secret
          TOKEN_EXPIRATION: 90904283492     # Example: set token expiration to 1 day (in ms)
        run: echo "Environment variables for testing have been set."
      - name: Build and Test
        run: mvn clean verify
